Error: RelaxObj: multiple (see details)
* use . indexing instead of set() (Constructor)
* use explicit arrayfun with non uniform output (check)
* remove error in getData and getDataInfo to avoid problem if no output